spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: bank
    password: bank
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  jwt:
    secret: "change-this-in-prod-please-please-please"
    expirationSeconds: 7200

server:
  port: 8080
  error:
    include-message: always

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/bank
    username: bank
    password: bank
